@url = http://localhost:3000

@Content-Type = application/json

###
# 注册
POST {{url}}/user/api/v1/register HTTP/1.1
Content-Type: application/json

{
  "phone": "13790091224",
  "upwd": "123456"
}

###
# 登陆
POST {{url}}/user/api/v1/login HTTP/1.1
Content-Type: application/json

{
  "phone": "13790091222",
  "upwd": "123456"
}

###
# 更新名字
PUT {{url}}/user/api/v1/updatename HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "uname": "h"
}


###
# 注销
GET {{url}}/user/api/v1/logout HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MywidW5hbWUiOiJ1c2VyX1RscURpVHdDRnEifSwiaWF0IjoxNTcxMjk0NjE2LCJleHAiOjE1NzM4ODY2MTZ9.ogrgjuIVjRzkyitWPVf6TQCWM9zs8lo0bwX3rpHXRn4

###
# 参看用户详情
GET {{url}}/user/api/v1/detail HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8

###
# 更新性别
PUT {{url}}/user/api/v1/updatesex HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "gender": "-1"
}

###
# 更新生日
PUT {{url}}/user/api/v1/updatebirth HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "birthday": "1996-1-1"
}

###
# 更新城市
PUT {{url}}/user/api/v1/updatecity HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "city": "顺德"
}

###
# 更新简介
PUT {{url}}/user/api/v1/updateintr HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "intr": "好帅"
}

###
# 关注
POST  {{url}}/user/api/v1/focus HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

{
  "uid": 3
}

###
# 查看用户详情
GET   {{url}}/user/api/v1/detail/2 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MiwidW5hbWUiOiJ1c2VyX3MxVEVLVWJpZFIifSwiaWF0IjoxNTcxMzA5Nzc5LCJleHAiOjE1NzM5MDE3Nzl9.Ft5fxXLk-Olz8zQKYmRJGKxTu4evnwIBSKOFHg757z8
Content-Type: application/json

###
# 粉丝列表
get {{url}}/user/api/v1/fanslist HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

###
# 关注列表
get {{url}}/user/api/v1/focuslist HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json

###
# 主题列表
get {{url}}/group/api/v1/themelist HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
Content-Type: application/json


# 城市列表
###
GET  {{url}}/group/api/v1/citylist/1 HTTP/1.1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVpZCI6MSwidW5hbWUiOiJ1c2VyXzhhY2QxbHphNXgifSwiaWF0IjoxNTcxNTQwNjYwLCJleHAiOjE1NzQxMzI2NjB9.GdmQXAfLWJ73Zh_gT8-4G40qgm8RpMmBUcqTvCcS9P8
